// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace system_proxy {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class SystemProxyHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class SystemProxySettings {
 public:
  // Constructs an object setting all non-nullable fields.
  SystemProxySettings();

  // Constructs an object setting all fields.
  explicit SystemProxySettings(
    const std::string* http_proxy,
    const std::string* socks_proxy,
    const std::string* bypass);

  const std::string* http_proxy() const;
  void set_http_proxy(const std::string_view* value_arg);
  void set_http_proxy(std::string_view value_arg);

  const std::string* socks_proxy() const;
  void set_socks_proxy(const std::string_view* value_arg);
  void set_socks_proxy(std::string_view value_arg);

  const std::string* bypass() const;
  void set_bypass(const std::string_view* value_arg);
  void set_bypass(std::string_view value_arg);


 private:
  static SystemProxySettings FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class SystemProxyHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> http_proxy_;
  std::optional<std::string> socks_proxy_;
  std::optional<std::string> bypass_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class SystemProxyHostApi {
 public:
  SystemProxyHostApi(const SystemProxyHostApi&) = delete;
  SystemProxyHostApi& operator=(const SystemProxyHostApi&) = delete;
  virtual ~SystemProxyHostApi() {}
  virtual std::optional<FlutterError> SetSystemProxy(const SystemProxySettings& settings) = 0;
  virtual std::optional<FlutterError> RemoveSystemProxy() = 0;

  // The codec used by SystemProxyHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `SystemProxyHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    SystemProxyHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    SystemProxyHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  SystemProxyHostApi() = default;

};
}  // namespace system_proxy
#endif  // PIGEON_MESSAGES_G_H_
