// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace system_proxy {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// SystemProxySettings

SystemProxySettings::SystemProxySettings() {}

SystemProxySettings::SystemProxySettings(
  const std::string* http_proxy,
  const std::string* socks_proxy,
  const std::string* bypass)
 : http_proxy_(http_proxy ? std::optional<std::string>(*http_proxy) : std::nullopt),
    socks_proxy_(socks_proxy ? std::optional<std::string>(*socks_proxy) : std::nullopt),
    bypass_(bypass ? std::optional<std::string>(*bypass) : std::nullopt) {}

const std::string* SystemProxySettings::http_proxy() const {
  return http_proxy_ ? &(*http_proxy_) : nullptr;
}

void SystemProxySettings::set_http_proxy(const std::string_view* value_arg) {
  http_proxy_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SystemProxySettings::set_http_proxy(std::string_view value_arg) {
  http_proxy_ = value_arg;
}


const std::string* SystemProxySettings::socks_proxy() const {
  return socks_proxy_ ? &(*socks_proxy_) : nullptr;
}

void SystemProxySettings::set_socks_proxy(const std::string_view* value_arg) {
  socks_proxy_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SystemProxySettings::set_socks_proxy(std::string_view value_arg) {
  socks_proxy_ = value_arg;
}


const std::string* SystemProxySettings::bypass() const {
  return bypass_ ? &(*bypass_) : nullptr;
}

void SystemProxySettings::set_bypass(const std::string_view* value_arg) {
  bypass_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void SystemProxySettings::set_bypass(std::string_view value_arg) {
  bypass_ = value_arg;
}


EncodableList SystemProxySettings::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(http_proxy_ ? EncodableValue(*http_proxy_) : EncodableValue());
  list.push_back(socks_proxy_ ? EncodableValue(*socks_proxy_) : EncodableValue());
  list.push_back(bypass_ ? EncodableValue(*bypass_) : EncodableValue());
  return list;
}

SystemProxySettings SystemProxySettings::FromEncodableList(const EncodableList& list) {
  SystemProxySettings decoded;
  auto& encodable_http_proxy = list[0];
  if (!encodable_http_proxy.IsNull()) {
    decoded.set_http_proxy(std::get<std::string>(encodable_http_proxy));
  }
  auto& encodable_socks_proxy = list[1];
  if (!encodable_socks_proxy.IsNull()) {
    decoded.set_socks_proxy(std::get<std::string>(encodable_socks_proxy));
  }
  auto& encodable_bypass = list[2];
  if (!encodable_bypass.IsNull()) {
    decoded.set_bypass(std::get<std::string>(encodable_bypass));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(SystemProxySettings::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(SystemProxySettings)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<SystemProxySettings>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by SystemProxyHostApi.
const flutter::StandardMessageCodec& SystemProxyHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `SystemProxyHostApi` to handle messages through the `binary_messenger`.
void SystemProxyHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  SystemProxyHostApi* api) {
  SystemProxyHostApi::SetUp(binary_messenger, api, "");
}

void SystemProxyHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  SystemProxyHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.system_proxy.SystemProxyHostApi.setSystemProxy" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_settings_arg = args.at(0);
          if (encodable_settings_arg.IsNull()) {
            reply(WrapError("settings_arg unexpectedly null."));
            return;
          }
          const auto& settings_arg = std::any_cast<const SystemProxySettings&>(std::get<CustomEncodableValue>(encodable_settings_arg));
          std::optional<FlutterError> output = api->SetSystemProxy(settings_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.system_proxy.SystemProxyHostApi.removeSystemProxy" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->RemoveSystemProxy();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue SystemProxyHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue SystemProxyHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace system_proxy
